### ISSUE TITLE
Zim does not follow locale

### ISSUE THREAD

**Issue by lunaryorn** [flathub/org.zim_wiki.Zim#19]
I just realized that Zim doesn't use my locale when installed from flatpak:  All UI text is English.  I never bothered so far, because I simply assumed that Zim wasn't translated, but I've recently seen Zim on somebody else's system and UI text was fully localized.

And indeed, when installing from a system package (pacman in my case) text is localized as well.

I'm not sure if this is an issue in the flatpak build, or in my flatpak configuration, but I don't know how to debug this issue, for I'm not so familiar Zim's code and flatpak in general.

I'd appreciate any help 🙂

**Comment by jaap-karssenberg** [comment]
Zim uses standard "gettext" system based on environment variables like LANG
and LANGUAGE. No idea how flatpak deals with those.

--- Jaap

**Comment by cheese** [comment]
> To me it looks as if Zim does not correctly initialize the locale directory in a flatpak build, and incidentally the flatpak build used to patch this (see [da1eb72](https://github.com/flathub/org.zim_wiki.Zim/commit/da1eb724b5092d0f7299cb89666c2e4df6e516ea) and #1), but that patch no longer exists.

That's my fault. I should have done regression test when I dropped the patch during a major update.

**Comment by jaap-karssenberg** [comment]
This code snippet detects when zim is running from source. When the folder
does not exist, it expects the gettext environment to be properly
intialized. Would expect flatpak to have a standard environment - otherwise
all applications need to hardcode this.
