### ISSUE TITLE
Not showing in the store, but can be installed from command line

### ISSUE THREAD

**Issue by dsboger** [flathub/org.zim_wiki.Zim#2]
Is there a reason why this app is not showing in the Web store?

**Comment by TingPing** [comment]
Upstream is missing the `<launchable>` property in their appdata and there is also a bug on our end about app-id's that don't end in `.desktop`.

**Comment by nedrichards** [comment]
fwiw the app shows up in the Endless OS version of GNOME Software:

![screenshot from 2018-04-17 07-49-44](https://user-images.githubusercontent.com/302677/38853104-1e4defa0-4214-11e8-9786-e713b190eba4.png)

Agree that we need to improve visibility for this and a few other apps though.
