### ISSUE TITLE
Equation plugin can not find dependencies

### ISSUE THREAD

**Issue by dalanicolai** [flathub/org.zim_wiki.Zim#3]
I am on Fedora 28. When I install Zim from flathub I can not use equation editor as it does not find the dvipng and latex dependencies. The equation does work when Zim is installed via native repositories (.rpm)

**Comment by cheese** [comment]
Since an runtime extension of Tex Live is available now, I will make Zim flatpak use it if installed.
Further we can make Zim able to call host command, but it requires hacking Zim internal codes.
