### ISSUE TITLE
Wayland (Zim 0.70)

### ISSUE THREAD

**Issue by robertvazan** [flathub/org.zim_wiki.Zim#4]
Zim now runs on Gtk3 and thus on Wayland. There is a [release candidate](https://github.com/zim-desktop-wiki/zim-desktop-wiki/releases/tag/0.70-rc1) for it. Please update to this version.

**Comment by cheese** [comment]
zim 0.70 rc is still not stable enough to push to Flathub.
You can install rc2 from my personal Flatpak repo:
https://cheeselee.fedorapeople.org/flatpak-public/

**Comment by robertvazan** [comment]
It's probably better to wait for stable release then. Let's keep this issue open while we wait for stable release.
