### ISSUE TITLE
Zim won't follow symlinks to notebooks

### ISSUE THREAD

**Issue by henrythemouse** [flathub/org.zim_wiki.Zim#8]
If I store my notebooks in /mnt/files/docs/zim/notes and symlink that to ~/notes, Zim fails to load the notebook responding with "No such file or directory: " 

If I put the full path in, the error message cuts the path off and reports a similar error.
If I try to use the file picker it won't allow me to pick symlinks and doesn't even list the /mnt directory.
The deb package doesn't have these problems, I just wanted to use the flatpak to get the latest version. 

Thanks for providing flatpaks

**Comment by cheese** [comment]
Zim flatpak does not have access to /mnt directory by default. You may run `flatpak override --filesystem=/mnt/files org.zim_wiki.ZIm` to arthorzied Zim flatpak to access /mnt/files directory. And then re-run Zim flatpak.

**Comment by henrythemouse** [comment]
Thanks for the solution. I'm guessing that supporting /mnt is considered a security risk. So, it's not that flatpak has a problem with symlinks, just with /mnt.
Instead of using the flatpak override option I mounted the desired filesystem in my home dir. Works for me and I don't have to remember that I used a custom flatpak option.

Thanks again for the flatpak.
