### ISSUE TITLE
please enable spell check plugin

### ISSUE THREAD

**Issue by g1ocke** [flathub/org.zim_wiki.Zim#9]
please enable spell check plugin in the flatpak

**Comment by jaap-karssenberg** [comment]
May I recommend using the alternative dependency "gtkspellcheck" instead?
It has much fewer issues.

Regards,

Jaap

Op wo 24 apr. 2019 12:08 schreef Robin Lee <notifications@github.com>:

**Comment by g1ocke** [comment]
thank you for the fast implementation,
unfortunately, the plugin can not be configured, the button is greyed out...

![Screenshot from 2019-04-25 14-54-11](https://user-images.githubusercontent.com/14040247/56737148-0fc0d200-676a-11e9-85cb-c23c0cad4cd1.png)

**Comment by g1ocke** [comment]
the icon will not be displayed after activation

![zim_bug_01](https://user-images.githubusercontent.com/14040247/56738653-5106b100-676d-11e9-877f-e75cd0f63205.png)

**Comment by cheese** [comment]
You may ask latter questions upstream.

**Comment by g1ocke** [comment]
https://github.com/zim-desktop-wiki/zim-desktop-wiki/issues/817
